function [marker] = import_mocap_data(filename)
%IMPORT_MOCAP_DATA imports the .csv file generated by OptiTrack and stores
%                   the data in a way, that it can be used for the functions
%                   of Peter
%
% Input: FILENAME:  .csv file from OptiTrack
% Output: 

daten = readtable(filename);
daten = table2cell(daten);

% Extract Markernames
names = daten(1,:);
names = unique(names); % Remove duplicates
names = names(1,~any(cellfun('isempty', names), 1)); % Remove empty fields
names = names(1,~strncmp(names,'Unlabeled',9));
n_marker = size(names,2);
n_frames = size(daten(5:end,:),1);



% Extract Coordinates
for i = 1:n_marker
    R = ones(n_frames,4);
       for j = 1:size(daten,2)
        
          if strcmp(names(1,i),daten(1,j)) && strcmp(daten(4,j),'X')
              x = str2double(daten(5:end,j));
              R(:,1) = x';
          end
    
          if strcmp(names(1,i),daten(1,j)) && strcmp(daten(4,j),'Y')
              y = str2double(daten(5:end,j));
              R(:,2) = y';
          end
    
          if strcmp(names(1,i),daten(1,j)) && strcmp(daten(4,j),'Z')
              z = str2double(daten(5:end,j));
              R(:,3) = z';
          end
               
       end
       
       try
            if ~strncmp(names(1,i),'Unlabeled',9) % Ignore unlabelled markers
            marker_name = char(names(1,i));
                 R = R';
                 marker_array.(marker_name) = R;
            end
       catch ME
          switch ME.identifier
              case 'MATLAB:AddField:InvalidFieldName'
                  continue
              otherwise
                  rethrow(ME)                 
          end
       end
end



marker = marker_array;
end

